### ISSUE TITLE
Clearing for blueprints activates on hostile siege blueprints.

### ISSUE THREAD

**Issue by CodeOptimist** [alextd/RimWorld-ShareTheLoad#1]
Saw my miner making a solo suicide run toward hostile forces, wasn't sure what was going on. Then remembered seeing the setting in this awesome mod of yours. I've now flipped the setting.

![image](https://user-images.githubusercontent.com/52485/55043516-4507c200-4ffc-11e9-96c0-95c2857014c4.png)

Just thought you might like to know. :)
(P.S. Your mods are amazing; EnhancementPack is a must-have.)

**Comment by alextd** [comment]
Cool, easy fix.
