### ISSUE TITLE
Mod is hard built against specific Extended Storage assemblies

### ISSUE THREAD

**Issue by DoctorVanGogh** [alextd/RimWorld-ShareTheLoad#2]
Just a head's up: You've hard referenced certain ExtendedStorage assemblies. Very _specific_ versions of those assemblies - whatever was live in the root folder of the current-at-build-time distribution of ExtendedStorage on Steam.

That of course totally blows if there is any change in ES's assemblies and those version numbers no longer match.

I've got a ton of people over on ES reporting errors after an update
https://gist.githubusercontent.com/HugsLibRecordKeeper/ea2186cdffdac96565ac47d1e54ce6bd/raw/7e4cf6ffe191d12d17217ee087d078e6ab1ba8c2/output_log.txt

>JobDriver threw exception [...]
System.TypeLoadException: Could not load type 'ExtendedStorage.Building_ExtendedStorage' from assembly 'ExtendedStorage, _**Version=3.4.1.8646**_, Culture=neutral, PublicKeyToken=null'.
at (wrapper dynamic-method) **Verse.AI.ReservationManager.Reserve_Patch3** [...]

> Active Harmony patches:
> ...
> ReservationManager.Reserve: PRE: Share_The_Load.Reserve_Patch.Prefix, Replace_Stuff.Replace.ReserveSharing.Prefix, **Share_The_Load.Reserve_Patch_ES.Prefix**

The `3.4.1.8646` assembly is no longer current or distributed, so type load fails... so error spam ahoy ;)

I'll see if I cant come up with a way to uncouple your ES patch as a short term fix.

**Comment by DoctorVanGogh** [comment]
Check my [branch](https://github.com/DoctorVanGogh/RimWorld-ShareTheLoad/tree/historical/1.0) for a fix for the issue.

Can't do a PR since you don't have a "pre 1.1 updates" branch or tag, but I picked the last public commit before your last build of the 1.0 compatibility assembly (Feb 1st).

Same patch should work for RW 1.1/Harmony 2.0 (although Brainz may have renamed his `AccessTools` & `FastAccess` helper classes slightly).

**Comment by alextd** [comment]
Looks like I did this already
