### ISSUE TITLE
Old transpiler for WorkGiver_ConstructDeliverResources.ResourceDeliverJobFor 

### ISSUE THREAD

**Issue by masakitenchi** [alextd/RimWorld-ShareTheLoad#3]
In 1.4, Tynan had already made a change in their code, from
```CS
if (!pawn.Map.itemAvailability.ThingsAvailableAnywhere(need, pawn))
{
        flag = true;
        thingDefCountClass = need;
        break;
}
```
to
```CS
if (!pawn.Map.itemAvailability.ThingsAvailableAnywhere(need2, pawn))
{
        missingResources.Add(need2);
        if (FloatMenuMakerMap.makingFor != pawn)
        {
	        break;
        }
        continue;
}
```
So that it would be able to force pawn deliver non-primary resource, but still prevents pawn from actively delivering those resources. 
Why the game doesn't throw any error even with share the load active, is because since the transpiler cannot find the exact position to patch, it won't change the IL code at all:
```
// if (FloatMenuMakerMap.makingFor != pawn)
IL_0099: callvirt instance void class [mscorlib]System.Collections.Generic.List`1<class Verse.ThingDefCountClass>::Add(!0)
IL_009e: ldsfld class Verse.Pawn RimWorld.FloatMenuMakerMap::makingFor
IL_00a3: ldloc.3
IL_00a4: ldfld class RimWorld.WorkGiver_ConstructDeliverResources/'<>c__DisplayClass9_0' RimWorld.WorkGiver_ConstructDeliverResources/'<>c__DisplayClass9_1'::'CS$<>8__locals1'
IL_00a9: ldfld class Verse.Pawn RimWorld.WorkGiver_ConstructDeliverResources/'<>c__DisplayClass9_0'::pawn
IL_00ae: beq IL_031a

// break;
IL_00b3: leave IL_0336
```
So at the moment the transpiler should instead find `Opcodes.Leave` with its precedent code being beq, and copy that operand into itself.
If you have not enough time, I'd be happy to make a fork and submit a PR for this in 1.4.

**Comment by alextd** [comment]
Yah this is minor enough it's just on my todolist
